// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rUbQB0USpFEBoSO1kH6QYRTvl_OKPvo',
    appId:
        '1:796545909849:web:abb40c2cd60d583f87dd48', // Get this from Firebase Console
    messagingSenderId: '796545909849',
    projectId: 'to-do-list-2b175',
    authDomain: 'to-do-list-2b175.firebaseapp.com',
    storageBucket: 'to-do-list-2b175.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Lpd9Poyjx1QX8djSxPv8JcCYujmVOv0',
    appId: '1:796545909849:android:0fc96b3d44102cb287dd48',
    messagingSenderId: '796545909849',
    projectId: 'to-do-list-2b175',
    storageBucket: 'to-do-list-2b175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Lpd9Poyjx1QX8djSxPv8JcCYujmVOv0',
    appId: '1:796545909849:ios:a212f4d4c9ef542887dd48',
    messagingSenderId: '796545909849',
    projectId: 'to-do-list-2b175',
    storageBucket: 'to-do-list-2b175.appspot.com',
    iosBundleId: 'com.example.mini_todo_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Lpd9Poyjx1QX8djSxPv8JcCYujmVOv0',
    appId: 'your-macos-app-id',
    messagingSenderId: '796545909849',
    projectId: 'to-do-list-2b175',
    storageBucket: 'to-do-list-2b175.appspot.com',
    iosBundleId: 'com.example.mini_todo_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Lpd9Poyjx1QX8djSxPv8JcCYujmVOv0',
    appId: 'your-windows-app-id',
    messagingSenderId: '796545909849',
    projectId: 'to-do-list-2b175',
    storageBucket: 'to-do-list-2b175.appspot.com',
  );
}
